# Generated by Django 4.1.1 on 2022-09-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irismodel',
            name='petal_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='irismodel',
            name='petal_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='irismodel',
            name='sepal_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='irismodel',
            name='sepal_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
